server:
  port: 8091
spring:
  datasource:                                           # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource          # 数据源类型：HikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver          # mysql驱动
    url: jdbc:mysql://120.27.251.210:33306/foodie-shop?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true
    username: root
    password: 123456

  rabbitmq:
    addresses: 120.27.251.210:5672
    username: guest
    password: guest
    virtual-host: /
    # 最大超时时间
    connection-timeout: 15000
    # 启用消息确认模式
    publisher-confirms: true
    # 设置return消息，需要和mandatory一起配合使用
    publisher-returns: true
    template:
      mandatory: true

